### ISSUE TITLE
no album appearing

### ISSUE THREAD

**Issue by lgwapnitsky** [iksteen/pelican-albums#1]
i've created the album template, but no album is appearing in my page, nor are thumbnails being generated.

**Comment by iksteen** [comment]
Unfortunately, you haven't provided a lot of information. Could you answer the following questions:
- Which version of pelican do you use? 
- Which version of pelican-albums do you use? 
- How did you enable the pelican-albums plugin in your pelican config? 
- What have you set ALBUM_PATH to in your pelican config? 

Could you provide the output of a pelican run?

**Comment by iksteen** [comment]
Also, did you create a new page inside the album's folder (where the images reside)?

**Comment by iksteen** [comment]
Closing this issue due to lack of response and reproducibility.
